### ISSUE TITLE
Broken ace dependency on http://codingboard.org

### ISSUE THREAD

**Issue by krzysztof-jelski** [balopat/codingboard#49]
On http://codingboard.org it's impossible to share a code snippet. Page http://codingboard.org/boards/[board]/codesnippet fails to load because the link to ace.js is broken.

**Comment by sandromancuso** [comment]
Having the same problem.

**Comment by sandromancuso** [comment]
I can't promise but I'll try to have a look at it next week.

**Comment by balopat** [comment]
Uh-oh! Okay, I'll have a look at this tomorrow! Thanks @krzysztof-jelski and @sandromancuso!

**Comment by balopat** [comment]
fixed and deployed!
